project_id = "xmganxsmfvcbuffeelej"

[functions.chat]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.scan-receipt]
verify_jwt = false

[functions.parse-voice]
verify_jwt = false
