// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-transactions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Non authentifi\xE9. Connecte-toi \xE0 Mon Jeton pour utiliser cet outil." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-transactions.ts
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "Lister les transactions",
  description: "Liste les transactions (d\xE9penses et revenus) de l'utilisateur connect\xE9, filtrables par p\xE9riode et par type.",
  inputSchema: {
    from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date de d\xE9but (AAAA-MM-JJ)."),
    to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date de fin (AAAA-MM-JJ)."),
    type: z.enum(["expense", "income"]).optional().describe("Filtrer par type."),
    limit: z.number().int().min(1).max(200).default(50).describe("Nombre maximum de lignes.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("transactions").select("id, date, type, amount, note, merchant_name, categories(name), wallets(wallet_name)").order("date", { ascending: false }).limit(limit ?? 50);
    if (from) query = query.gte("date", from);
    if (to) query = query.lte("date", to);
    if (type) query = query.eq("type", type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((t) => ({
      id: t.id,
      date: t.date,
      type: t.type,
      amount: Number(t.amount),
      note: t.note ?? t.merchant_name ?? null,
      category: t.categories?.name ?? null,
      wallet: t.wallets?.wallet_name ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { transactions: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/add-transaction.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var add_transaction_default = defineTool2({
  name: "add_transaction",
  title: "Ajouter une transaction",
  description: "Enregistre une d\xE9pense ou un revenu pour l'utilisateur connect\xE9. La cat\xE9gorie et le portefeuille sont optionnels et retrouv\xE9s par leur nom.",
  inputSchema: {
    amount: z2.number().positive().describe("Montant (entier positif, devise du compte)."),
    type: z2.enum(["expense", "income"]).default("expense").describe("D\xE9pense ou revenu."),
    note: z2.string().trim().max(200).optional().describe("Libell\xE9 ou note."),
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date (AAAA-MM-JJ), aujourd'hui par d\xE9faut."),
    category: z2.string().trim().max(100).optional().describe("Nom d'une cat\xE9gorie existante."),
    wallet: z2.string().trim().max(100).optional().describe("Nom d'un portefeuille existant.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amount, type, note, date, category, wallet }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const userId = ctx.getUserId();
    if (!userId) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let categoryId = null;
    if (category) {
      const { data: data2 } = await supabase.from("categories").select("id").ilike("name", category).limit(1).maybeSingle();
      categoryId = data2?.id ?? null;
    }
    let walletId = null;
    if (wallet) {
      const { data: data2 } = await supabase.from("wallets").select("id").ilike("wallet_name", wallet).limit(1).maybeSingle();
      walletId = data2?.id ?? null;
    }
    const { data, error } = await supabase.from("transactions").insert({
      user_id: userId,
      amount,
      type: type ?? "expense",
      note: note ?? null,
      date: date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      category_id: categoryId,
      wallet_id: walletId
    }).select("id, date, type, amount, note").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Transaction enregistr\xE9e : ${JSON.stringify(data)}` }],
      structuredContent: {
        transaction: data,
        categoryMatched: category ? categoryId !== null : null,
        walletMatched: wallet ? walletId !== null : null
      }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var financial_summary_default = defineTool3({
  name: "get_financial_summary",
  title: "R\xE9sum\xE9 financier du mois",
  description: "Retourne les revenus, d\xE9penses, solde et le d\xE9tail par cat\xE9gorie pour un mois donn\xE9 (mois courant par d\xE9faut).",
  inputSchema: {
    month: z3.number().int().min(1).max(12).optional().describe("Mois (1-12)."),
    year: z3.number().int().min(2e3).max(2100).optional().describe("Ann\xE9e.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month, year }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const now = /* @__PURE__ */ new Date();
    const m = month ?? now.getUTCMonth() + 1;
    const y = year ?? now.getUTCFullYear();
    const start = `${y}-${String(m).padStart(2, "0")}-01`;
    const endDate = new Date(Date.UTC(y, m, 0));
    const end = endDate.toISOString().slice(0, 10);
    const { data, error } = await supabase.from("transactions").select("type, amount, categories(name)").gte("date", start).lte("date", end).limit(2e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let income = 0;
    let expense = 0;
    const byCategory = {};
    for (const t of data ?? []) {
      const amount = Number(t.amount) || 0;
      if (t.type === "income") {
        income += amount;
      } else {
        expense += amount;
        const name = t.categories?.name ?? "Sans cat\xE9gorie";
        byCategory[name] = (byCategory[name] ?? 0) + amount;
      }
    }
    const summary = {
      period: { month: m, year: y, from: start, to: end },
      income,
      expense,
      balance: income - expense,
      expensesByCategory: Object.entries(byCategory).map(([category, total]) => ({ category, total })).sort((a, b) => b.total - a.total)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-wallets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var list_wallets_default = defineTool4({
  name: "list_wallets_and_categories",
  title: "Portefeuilles et cat\xE9gories",
  description: "Liste les portefeuilles et les cat\xE9gories de l'utilisateur connect\xE9, utiles pour renseigner une nouvelle transaction.",
  inputSchema: {
    kind: z4.enum(["all", "wallets", "categories"]).default("all").describe("Ce qu'il faut retourner.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const want = kind ?? "all";
    const result = {};
    if (want === "all" || want === "wallets") {
      const { data, error } = await supabase.from("wallets").select("id, wallet_name, currency, initial_balance").limit(100);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.wallets = data ?? [];
    }
    if (want === "all" || want === "categories") {
      const { data, error } = await supabase.from("categories").select("id, name, type").limit(200);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      result.categories = data ?? [];
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-budgets.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z5 } from "npm:zod@^3.25.76";
var list_budgets_default = defineTool5({
  name: "list_budgets",
  title: "Budgets du mois",
  description: "Liste les budgets par cat\xE9gorie du mois demand\xE9 avec le montant d\xE9j\xE0 d\xE9pens\xE9 et le reste disponible.",
  inputSchema: {
    month: z5.number().int().min(1).max(12).optional().describe("Mois (1-12)."),
    year: z5.number().int().min(2e3).max(2100).optional().describe("Ann\xE9e.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month, year }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const now = /* @__PURE__ */ new Date();
    const m = month ?? now.getUTCMonth() + 1;
    const y = year ?? now.getUTCFullYear();
    const start = `${y}-${String(m).padStart(2, "0")}-01`;
    const end = new Date(Date.UTC(y, m, 0)).toISOString().slice(0, 10);
    const { data: budgets, error: budgetError } = await supabase.from("category_budgets").select("id, category_id, budget_amount, categories(name)").eq("month", m).eq("year", y).limit(200);
    if (budgetError) return { content: [{ type: "text", text: budgetError.message }], isError: true };
    const { data: tx, error: txError } = await supabase.from("transactions").select("category_id, amount").eq("type", "expense").gte("date", start).lte("date", end).limit(2e3);
    if (txError) return { content: [{ type: "text", text: txError.message }], isError: true };
    const spentByCategory = {};
    for (const t of tx ?? []) {
      if (!t.category_id) continue;
      spentByCategory[t.category_id] = (spentByCategory[t.category_id] ?? 0) + (Number(t.amount) || 0);
    }
    const rows = (budgets ?? []).map((b) => {
      const budget = Number(b.budget_amount) || 0;
      const spent = spentByCategory[b.category_id] ?? 0;
      return {
        category: b.categories?.name ?? "Sans cat\xE9gorie",
        budget,
        spent,
        remaining: budget - spent,
        usedPercent: budget > 0 ? Math.round(spent / budget * 100) : null
      };
    });
    const payload = { period: { month: m, year: y }, budgets: rows };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xmganxsmfvcbuffeelej";
var mcp_default = defineMcp({
  name: "mon-jeton",
  title: "MON JETON",
  version: "0.1.0",
  instructions: "Outils de gestion financi\xE8re personnelle Mon Jeton. Permet de lister et cr\xE9er des transactions, consulter le r\xE9sum\xE9 financier mensuel, les budgets, les portefeuilles et les cat\xE9gories de l'utilisateur connect\xE9. Les montants sont dans la devise du compte (FCFA par d\xE9faut).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_transactions_default, add_transaction_default, financial_summary_default, list_budgets_default, list_wallets_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
